"""First migration

Revision ID: 4f41ce00f440
Revises: 
Create Date: 2025-08-26 13:08:33.075172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f41ce00f440'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_marca', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_marca')
    )
    op.create_index(op.f('ix_marcas_id'), 'marcas', ['id'], unique=False)
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor_fipe', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_id'), 'modelos', ['id'], unique=False)
    op.create_table('carros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_cadastro', sa.DateTime(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('combustivel', sa.String(), nullable=False),
    sa.Column('num_portas', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carros_id'), 'carros', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carros_id'), table_name='carros')
    op.drop_table('carros')
    op.drop_index(op.f('ix_modelos_id'), table_name='modelos')
    op.drop_table('modelos')
    op.drop_index(op.f('ix_marcas_id'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
